# Version updates paused at the repository owner's request.
version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "CI"
